/*  ===================================================================
    type definitions
    ====================================================================*/

typedef BOOL	(WINAPI *BitBlt_Type)(HDC, int, int, int, int, HDC, int, int, DWORD);
typedef HDC		(WINAPI *CreateCompatibleDC_Type)(HDC);
typedef HDC		(WINAPI *CreateDCA_Type)(LPCSTR, LPCSTR, LPCSTR, const DEVMODE *);
typedef HDC		(WINAPI *CreateDCW_Type)(LPWSTR, LPWSTR, LPWSTR, const DEVMODE *);
typedef HFONT	(WINAPI *CreateFont_Type)(int, int, int, int, int, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, LPCTSTR);
typedef HFONT	(WINAPI *CreateFontIndirect_Type)(const LOGFONT *);
typedef HPALETTE(WINAPI *GDICreatePalette_Type)(CONST LOGPALETTE *);
typedef HDWP	(WINAPI *DeferWindowPos_Type)(HDWP, HWND, HWND, int, int, int, int, UINT);
typedef BOOL	(WINAPI *DeleteDC_Type)(HDC);
typedef BOOL	(WINAPI *ExtTextOutW_Type)(HDC, int, int, UINT, const RECT *, LPCWSTR, UINT, const INT *);
typedef BOOL	(WINAPI *ExtTextOutA_Type)(HDC, int, int, UINT, const RECT *, LPCSTR, UINT, const INT *);
typedef int		(WINAPI *GetClipBox_Type)(HDC, LPRECT);
typedef BOOL	(WINAPI *GetDCOrgEx_Type)(HDC, LPPOINT);
typedef DWORD	(WINAPI *GetRegionData_Type)(HRGN, DWORD, LPRGNDATA);
typedef int		(WINAPI *GetDeviceCaps_Type)(HDC, int);
typedef BOOL	(WINAPI *GetDeviceGammaRamp_Type)(HDC, LPVOID);
typedef BOOL	(WINAPI *GetSystemPaletteEntries_Type)(HDC, UINT, UINT, LPPALETTEENTRY);
typedef UINT	(WINAPI *GetPaletteEntries_Type)(HPALETTE, UINT, UINT, LPPALETTEENTRY);
typedef UINT	(WINAPI *GetSystemPaletteUse_Type)(HDC);
typedef BOOL	(WINAPI *PatBlt_Type)(HDC, int, int, int, int, DWORD);
typedef BOOL	(WINAPI *Polyline_Type)(HDC, const POINT *, int);
typedef UINT	(WINAPI *RealizePalette_Type)(HDC);
typedef BOOL	(WINAPI *Rectangle_Type)(HDC, int, int, int, int);
typedef BOOL	(WINAPI *RestoreDC_Type)(HDC, int);
typedef int		(WINAPI *SaveDC_Type)(HDC);
typedef HPALETTE(WINAPI *SelectPalette_Type)(HDC, HPALETTE, BOOL);
typedef COLORREF (WINAPI *SetBkColor_Type)(HDC, COLORREF);
typedef BOOL	(WINAPI *SetDeviceGammaRamp_Type)(HDC, LPVOID);
typedef COLORREF(WINAPI *SetTextColor_Type)(HDC, COLORREF);
typedef BOOL	(WINAPI *StretchBlt_Type)(HDC, int, int, int, int, HDC, int, int, int, int, DWORD);
typedef int		(WINAPI *StretchDIBits_Type)(HDC, int, int, int, int, int, int, int, int, const VOID *, const BITMAPINFO *, UINT, DWORD);
typedef BOOL	(WINAPI *TextOutA_Type)(HDC, int, int, LPCTSTR, int);
typedef BOOL	(WINAPI *TextOutW_Type)(HDC, int, int, LPCWSTR, int);
typedef BOOL	(WINAPI *PolyBezier_Type)(HDC, const POINT *, DWORD);
typedef BOOL	(WINAPI *PolyBezierTo_Type)(HDC, const POINT *, DWORD);
typedef BOOL	(WINAPI *PolylineTo_Type)(HDC, const POINT *, DWORD);
typedef BOOL	(WINAPI *PolyDraw_Type)(HDC, const POINT *, const BYTE *, int);
typedef BOOL	(WINAPI *MoveToEx_Type)(HDC, int, int, LPPOINT);
typedef BOOL	(WINAPI *ArcTo_Type)(HDC, int, int, int, int, int, int, int, int);
typedef BOOL	(WINAPI *LineTo_Type)(HDC, int, int);
typedef int		(WINAPI *SetDIBitsToDevice_Type)(HDC, int, int, DWORD, DWORD, int, int, UINT, UINT, const VOID *, const BITMAPINFO *, UINT);
typedef HBITMAP (WINAPI *CreateCompatibleBitmap_Type)(HDC, int, int);
typedef COLORREF(WINAPI *SetPixel_Type)(HDC, int, int, COLORREF);
typedef BOOL	(WINAPI *Ellipse_Type)(HDC, int, int, int, int);
typedef BOOL	(WINAPI *Polygon_Type)(HDC, const POINT *, int);
typedef BOOL	(WINAPI *Arc_Type)(HDC, int, int, int, int, int, int, int, int);
typedef BOOL	(WINAPI *MaskBlt_Type)(HDC, int, int, int, int, HDC, int, int, HBITMAP, int, int, DWORD);
typedef BOOL	(WINAPI *SetViewportOrgEx_Type)(HDC, int, int, LPPOINT);
typedef BOOL	(WINAPI *SetViewportExtEx_Type)(HDC, int, int, LPSIZE);
typedef BOOL	(WINAPI *GetViewportOrgEx_Type)(HDC, LPPOINT);
typedef BOOL	(WINAPI *GetViewportExtEx_Type)(HDC, LPPOINT);
typedef BOOL	(WINAPI *GetWindowOrgEx_Type)(HDC, LPPOINT);
typedef BOOL	(WINAPI *SetWindowExtEx_Type)(HDC, int, int, LPPOINT);
typedef BOOL	(WINAPI *SetWindowOrgEx_Type)(HDC, int, int, LPPOINT);
typedef BOOL	(WINAPI *GetCurrentPositionEx_Type)(HDC, LPPOINT);
typedef BOOL	(WINAPI *AnimatePalette_Type)(HPALETTE, UINT, UINT, const PALETTEENTRY *);
typedef UINT	(WINAPI *SetSystemPaletteUse_Type)(HDC, UINT);
typedef BOOL	(WINAPI *GDISetPixelFormat_Type)(HDC, int, const PIXELFORMATDESCRIPTOR *);
typedef BOOL	(WINAPI *GDIGetPixelFormat_Type)(HDC);
typedef int		(WINAPI *ChoosePixelFormat_Type)(HDC, const PIXELFORMATDESCRIPTOR *);
typedef int		(WINAPI *DescribePixelFormat_Type)(HDC, int, UINT, LPPIXELFORMATDESCRIPTOR);
typedef DWORD	(WINAPI *GetObjectType_Type)(HGDIOBJ);
typedef int		(WINAPI *SetDIBits_Type)(HDC, HBITMAP, UINT, UINT, const VOID *, const BITMAPINFO *, UINT);
typedef COLORREF (WINAPI *GetPixel_Type)(HDC, int, int);
typedef BOOL	(WINAPI *PlgBlt_Type)(HDC, const POINT *, HDC, int, int, int, int, HBITMAP, int, int);
typedef BOOL	(WINAPI *SetPixelV_Type)(HDC, int, int, COLORREF);
typedef BOOL	(WINAPI *Chord_Type)(HDC, int, int, int, int, int, int, int, int);
typedef BOOL	(WINAPI *PolyTextOutA_Type)(HDC, const POLYTEXTA *, int);
typedef BOOL	(WINAPI *PolyTextOutW_Type)(HDC, const POLYTEXTW *, int);
typedef int		(WINAPI *GetDIBits_Type)(HDC, HBITMAP, UINT, UINT, LPVOID, LPBITMAPINFO, UINT);
typedef HBITMAP (WINAPI *CreateDIBitmap_Type)(HDC, BITMAPINFOHEADER *, DWORD, const VOID *, const BITMAPINFO *, UINT);
typedef HBITMAP (WINAPI *CreateDIBSection_Type)(HDC, const BITMAPINFO *, UINT, VOID **, HANDLE, DWORD);
typedef HBITMAP (WINAPI *CreateDiscardableBitmap_Type)(HDC, int, int);
typedef BOOL	(WINAPI *ExtFloodFill_Type)(HDC, int, int, COLORREF, UINT);
typedef BOOL	(WINAPI *GdiAlphaBlend_Type)(HDC, int, int, int, int, HDC, int, int, int, int, BLENDFUNCTION);
typedef BOOL	(WINAPI *GdiGradientFill_Type)(HDC, PTRIVERTEX, ULONG, PVOID, ULONG, ULONG);
typedef BOOL	(WINAPI *GdiTransparentBlt_Type)(HDC, int, int, int, int, HDC, int, int, int, int, UINT);
typedef BOOL	(WINAPI *Pie_Type)(HDC, int, int, int, int, int, int, int, int);
typedef BOOL	(WINAPI *AngleArc_Type)(HDC, int, int, DWORD, FLOAT, FLOAT);
typedef BOOL	(WINAPI *PolyPolyline_Type)(HDC, const POINT *, const DWORD *, DWORD);
typedef BOOL	(WINAPI *FillRgn_Type)(HDC, HRGN, HBRUSH);
typedef BOOL	(WINAPI *FrameRgn_Type)(HDC, HRGN, HBRUSH, int, int);
typedef BOOL	(WINAPI *InvertRgn_Type)(HDC, HRGN);
typedef BOOL	(WINAPI *PaintRgn_Type)(HDC, HRGN);
typedef int		(WINAPI *SetMapMode_Type)(HDC, int);
typedef BOOL	(WINAPI *RoundRect_Type)(HDC, int, int, int, int, int, int);
typedef BOOL	(WINAPI *PolyPolygon_Type)(HDC, const POINT *, const INT *, int);
//typedef BOOL	(WINAPI *DPtoLP_Type)(HDC, LPPOINT, int);
typedef BOOL	(WINAPI *PlayEnhMetaFile_Type)(HDC, HENHMETAFILE, const RECT *);
typedef UINT	(WINAPI *SetPaletteEntries_Type)(HPALETTE, UINT, UINT, const PALETTEENTRY *);
typedef int		(WINAPI *SetROP2_Type)(HDC, int);
typedef BOOL	(WINAPI *GetTextExtentPointA_Type)(HDC, LPCTSTR, int, LPSIZE);
typedef BOOL	(WINAPI *GetTextExtentPoint32A_Type)(HDC, LPCTSTR, int, LPSIZE);
typedef HGDIOBJ (WINAPI *SelectObject_Type)(HDC, HGDIOBJ);
typedef BOOL	(WINAPI *DeleteObject_Type)(HGDIOBJ);
typedef int		(WINAPI *SelectClipRgn_Type)(HDC, HRGN);
typedef int		(WINAPI *ExtSelectClipRgn_Type)(HDC, HRGN, int);
typedef int		(WINAPI *GetClipRgn_Type)(HDC, HRGN);
typedef BOOL	(WINAPI *CreateScalableFontResourceA_Type)(DWORD, LPCTSTR, LPCTSTR, LPCTSTR);
typedef BOOL	(WINAPI *CreateScalableFontResourceW_Type)(DWORD, LPCWSTR, LPCWSTR, LPCWSTR);
typedef int		(WINAPI *AddFontResourceA_Type)(LPCTSTR);
typedef int		(WINAPI *AddFontResourceW_Type)(LPCWSTR);
typedef int		(WINAPI *OffsetClipRgn_Type)(HDC, int, int);
typedef int		(WINAPI *HandleClipRect_Type)(HDC, int, int, int, int);

/*  ===================================================================
    hooked APIs real pointers
    ====================================================================*/

DXWEXTERN BitBlt_Type pGDIBitBlt DXWINITIALIZED;
DXWEXTERN CreateCompatibleDC_Type pGDICreateCompatibleDC DXWINITIALIZED;
DXWEXTERN CreateDCA_Type pGDICreateDCA DXWINITIALIZED;
DXWEXTERN CreateDCW_Type pGDICreateDCW DXWINITIALIZED;
DXWEXTERN CreateFont_Type pGDICreateFontA DXWINITIALIZED;
DXWEXTERN CreateFontIndirect_Type pGDICreateFontIndirectA DXWINITIALIZED;
DXWEXTERN GDICreatePalette_Type pGDICreatePalette DXWINITIALIZED;
DXWEXTERN DeferWindowPos_Type pGDIDeferWindowPos DXWINITIALIZED;
DXWEXTERN DeleteDC_Type pGDIDeleteDC DXWINITIALIZED;
DXWEXTERN ExtTextOutW_Type pExtTextOutW DXWINITIALIZED;
DXWEXTERN ExtTextOutA_Type pExtTextOutA DXWINITIALIZED;
DXWEXTERN GetClipBox_Type pGDIGetClipBox DXWINITIALIZED;
DXWEXTERN GetRegionData_Type pGetRegionData DXWINITIALIZED;
DXWEXTERN GetDCOrgEx_Type pGetDCOrgEx DXWINITIALIZED;
DXWEXTERN GetDeviceCaps_Type pGDIGetDeviceCaps DXWINITIALIZED;
DXWEXTERN GetDeviceGammaRamp_Type pGDIGetDeviceGammaRamp DXWINITIALIZED;
DXWEXTERN GetSystemPaletteEntries_Type pGDIGetSystemPaletteEntries DXWINITIALIZED;
DXWEXTERN GetPaletteEntries_Type pGetPaletteEntries DXWINITIALIZED;
DXWEXTERN GetSystemPaletteUse_Type pGetSystemPaletteUse DXWINITIALIZED;
DXWEXTERN PatBlt_Type pGDIPatBlt DXWINITIALIZED;
DXWEXTERN Polyline_Type pPolyline DXWINITIALIZED;
DXWEXTERN RealizePalette_Type pGDIRealizePalette DXWINITIALIZED;
DXWEXTERN Rectangle_Type pGDIRectangle DXWINITIALIZED;
DXWEXTERN RestoreDC_Type pGDIRestoreDC DXWINITIALIZED;
DXWEXTERN SaveDC_Type pGDISaveDC DXWINITIALIZED;
DXWEXTERN SelectPalette_Type pGDISelectPalette DXWINITIALIZED;
DXWEXTERN SetBkColor_Type pGDISetBkColor DXWINITIALIZED;
DXWEXTERN SetDeviceGammaRamp_Type pGDISetDeviceGammaRamp DXWINITIALIZED;
DXWEXTERN SetTextColor_Type pGDISetTextColor DXWINITIALIZED;
DXWEXTERN StretchBlt_Type pGDIStretchBlt DXWINITIALIZED;
DXWEXTERN StretchDIBits_Type pStretchDIBits DXWINITIALIZED;
DXWEXTERN TextOutA_Type pGDITextOutA DXWINITIALIZED;
DXWEXTERN TextOutW_Type pGDITextOutW DXWINITIALIZED;
DXWEXTERN LineTo_Type pLineTo DXWINITIALIZED;
DXWEXTERN ArcTo_Type pArcTo DXWINITIALIZED;
DXWEXTERN MoveToEx_Type pMoveToEx DXWINITIALIZED;
DXWEXTERN PolyDraw_Type pPolyDraw DXWINITIALIZED;
DXWEXTERN PolylineTo_Type pPolylineTo DXWINITIALIZED;
DXWEXTERN PolyBezier_Type pPolyBezier DXWINITIALIZED;
DXWEXTERN PolyBezierTo_Type pPolyBezierTo DXWINITIALIZED;
DXWEXTERN SetDIBitsToDevice_Type pSetDIBitsToDevice DXWINITIALIZED;
DXWEXTERN CreateCompatibleBitmap_Type pCreateCompatibleBitmap DXWINITIALIZED;
DXWEXTERN SetPixel_Type pSetPixel DXWINITIALIZED;
DXWEXTERN Ellipse_Type pEllipse DXWINITIALIZED;
DXWEXTERN Polygon_Type pPolygon DXWINITIALIZED;
DXWEXTERN Arc_Type pArc DXWINITIALIZED;
DXWEXTERN MaskBlt_Type pMaskBlt DXWINITIALIZED;
DXWEXTERN SetViewportOrgEx_Type pSetViewportOrgEx DXWINITIALIZED;
DXWEXTERN SetViewportExtEx_Type pSetViewportExtEx DXWINITIALIZED;
DXWEXTERN GetViewportOrgEx_Type pGetViewportOrgEx DXWINITIALIZED;
DXWEXTERN GetViewportExtEx_Type pGetViewportExtEx DXWINITIALIZED;
DXWEXTERN SetWindowOrgEx_Type pSetWindowExtEx DXWINITIALIZED;
DXWEXTERN GetWindowOrgEx_Type pGetWindowOrgEx DXWINITIALIZED;
DXWEXTERN SetWindowOrgEx_Type pSetWindowOrgEx DXWINITIALIZED;
DXWEXTERN GetCurrentPositionEx_Type pGetCurrentPositionEx DXWINITIALIZED;
DXWEXTERN CreateScalableFontResourceA_Type pCreateScalableFontResourceA DXWINITIALIZED;
DXWEXTERN CreateScalableFontResourceW_Type pCreateScalableFontResourceW DXWINITIALIZED;
DXWEXTERN AddFontResourceA_Type pAddFontResourceA DXWINITIALIZED;
DXWEXTERN AddFontResourceW_Type pAddFontResourceW DXWINITIALIZED;
DXWEXTERN AddFontResourceA_Type pRemoveFontResourceA DXWINITIALIZED;
DXWEXTERN AddFontResourceW_Type pRemoveFontResourceW DXWINITIALIZED;
DXWEXTERN AnimatePalette_Type pAnimatePalette DXWINITIALIZED;
DXWEXTERN SetSystemPaletteUse_Type pSetSystemPaletteUse DXWINITIALIZED;
DXWEXTERN GDISetPixelFormat_Type pGDISetPixelFormat DXWINITIALIZED;
DXWEXTERN GDIGetPixelFormat_Type pGDIGetPixelFormat DXWINITIALIZED;
DXWEXTERN ChoosePixelFormat_Type pChoosePixelFormat DXWINITIALIZED;
DXWEXTERN DescribePixelFormat_Type pDescribePixelFormat DXWINITIALIZED;
DXWEXTERN GetObjectType_Type pGetObjectType DXWINITIALIZED;
DXWEXTERN SetDIBits_Type pSetDIBits DXWINITIALIZED;
DXWEXTERN GetPixel_Type pGetPixel DXWINITIALIZED;
DXWEXTERN PlgBlt_Type pPlgBlt DXWINITIALIZED;
DXWEXTERN SetPixelV_Type pSetPixelV DXWINITIALIZED;
DXWEXTERN Chord_Type pChord DXWINITIALIZED;
DXWEXTERN PolyTextOutA_Type pPolyTextOutA DXWINITIALIZED;
DXWEXTERN PolyTextOutW_Type pPolyTextOutW DXWINITIALIZED;
DXWEXTERN GetDIBits_Type pGetDIBits DXWINITIALIZED;
DXWEXTERN CreateDIBitmap_Type pCreateDIBitmap DXWINITIALIZED;
DXWEXTERN CreateDIBSection_Type pCreateDIBSection DXWINITIALIZED;
DXWEXTERN CreateDiscardableBitmap_Type pCreateDiscardableBitmap DXWINITIALIZED;
DXWEXTERN ExtFloodFill_Type pExtFloodFill DXWINITIALIZED;
DXWEXTERN GdiAlphaBlend_Type pGdiAlphaBlend DXWINITIALIZED;
DXWEXTERN GdiGradientFill_Type pGdiGradientFill DXWINITIALIZED;
DXWEXTERN GdiTransparentBlt_Type pGdiTransparentBlt DXWINITIALIZED;
DXWEXTERN Pie_Type pPie DXWINITIALIZED;
DXWEXTERN AngleArc_Type pAngleArc DXWINITIALIZED;
DXWEXTERN PolyPolyline_Type pPolyPolyline DXWINITIALIZED;
DXWEXTERN FillRgn_Type pFillRgn DXWINITIALIZED;
DXWEXTERN FrameRgn_Type pFrameRgn DXWINITIALIZED;
DXWEXTERN InvertRgn_Type pInvertRgn DXWINITIALIZED;
DXWEXTERN PaintRgn_Type pPaintRgn DXWINITIALIZED;
DXWEXTERN SetMapMode_Type pSetMapMode DXWINITIALIZED;
DXWEXTERN RoundRect_Type pRoundRect DXWINITIALIZED;
DXWEXTERN PolyPolygon_Type pPolyPolygon DXWINITIALIZED;
//DXWEXTERN DPtoLP_Type pDPtoLP DXWINITIALIZED;
DXWEXTERN PlayEnhMetaFile_Type pPlayEnhMetaFile DXWINITIALIZED;
DXWEXTERN SetPaletteEntries_Type pSetPaletteEntries DXWINITIALIZED;
DXWEXTERN SetROP2_Type pSetROP2 DXWINITIALIZED;
DXWEXTERN GetTextExtentPointA_Type pGetTextExtentPointA DXWINITIALIZED;
DXWEXTERN GetTextExtentPoint32A_Type pGetTextExtentPoint32A DXWINITIALIZED;
DXWEXTERN SelectObject_Type pSelectObject DXWINITIALIZED;
DXWEXTERN DeleteObject_Type pDeleteObject DXWINITIALIZED;
DXWEXTERN SelectClipRgn_Type pSelectClipRgn DXWINITIALIZED;
DXWEXTERN ExtSelectClipRgn_Type pExtSelectClipRgn DXWINITIALIZED;
DXWEXTERN GetClipRgn_Type pGetClipRgn DXWINITIALIZED;
DXWEXTERN OffsetClipRgn_Type pOffsetClipRgn DXWINITIALIZED;
DXWEXTERN HandleClipRect_Type pExcludeClipRect DXWINITIALIZED;
DXWEXTERN HandleClipRect_Type pIntersectClipRect DXWINITIALIZED;

/*  ===================================================================
    hook procedures (possibly more than one per each API...)
    ====================================================================*/

extern BOOL WINAPI extGDIBitBlt(HDC, int, int, int, int, HDC, int, int, DWORD);
extern HDC WINAPI extGDICreateCompatibleDC(HDC);
extern HDC WINAPI extGDICreateDCA(LPSTR, LPSTR, LPSTR, CONST DEVMODE *);
extern HDC WINAPI extGDICreateDCW(LPWSTR, LPWSTR, LPWSTR, CONST DEVMODE *);
extern HFONT WINAPI extCreateFontA(int, int, int, int, int, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, LPCTSTR);
extern HFONT WINAPI extCreateFontIndirectA(const LOGFONT *);
extern HPALETTE WINAPI extGDICreatePalette(CONST LOGPALETTE *);
extern HDWP WINAPI extDeferWindowPos(HDWP, HWND, HWND, int, int, int, int, UINT);
extern BOOL WINAPI extExtTextOutW(HDC, int, int, UINT, const RECT *, LPCWSTR, UINT, const INT *);
extern BOOL WINAPI extExtTextOutA(HDC, int, int, UINT, const RECT *, LPCSTR, UINT, const INT *);
extern BOOL WINAPI extGDIDeleteDC(HDC);
extern int WINAPI extGetClipBox(HDC, LPRECT);
extern BOOL WINAPI extGetDCOrgEx(HDC, LPPOINT);
extern DWORD WINAPI extGetRegionData(HRGN, DWORD, LPRGNDATA);
extern int WINAPI extGetDeviceCaps(HDC, int);
extern BOOL WINAPI extGetDeviceGammaRamp(HDC, LPVOID);
extern UINT WINAPI extGetSystemPaletteEntries(HDC, UINT, UINT, LPPALETTEENTRY);
extern UINT WINAPI extGetPaletteEntries(HPALETTE, UINT, UINT, LPPALETTEENTRY);
extern UINT WINAPI extGetSystemPaletteUse(HDC);
extern BOOL WINAPI extGDIPatBlt(HDC, int, int, int, int, DWORD);
extern BOOL WINAPI extPolyline(HDC, const POINT *, int);
extern UINT WINAPI extRealizePalette(HDC);
extern BOOL WINAPI extRectangle(HDC, int, int, int, int);
extern BOOL WINAPI extGDIRestoreDC(HDC, int);
extern int WINAPI extGDISaveDC(HDC);
extern HPALETTE WINAPI extSelectPalette(HDC, HPALETTE, BOOL);
extern BOOL WINAPI extSetDeviceGammaRamp(HDC, LPVOID);
extern BOOL WINAPI extGDIStretchBlt(HDC, int, int, int, int, HDC, int, int, int, int, DWORD);
extern int WINAPI extStretchDIBits(HDC, int, int, int, int, int, int, int, int, const VOID *, const BITMAPINFO *, UINT, DWORD);
extern BOOL WINAPI extTextOutA(HDC, int, int, LPCTSTR, int);
extern BOOL WINAPI extTextOutW(HDC, int, int, LPCWSTR, int);
extern BOOL WINAPI extPolyBezier(HDC, const POINT *, DWORD);
extern BOOL WINAPI extPolyBezierTo(HDC, const POINT *, DWORD);
extern BOOL WINAPI extPolylineTo(HDC, const POINT *, DWORD);
extern BOOL WINAPI extPolyDraw(HDC, const POINT *, const BYTE *, int);
extern BOOL WINAPI extMoveToEx(HDC, int, int, LPPOINT);
extern BOOL WINAPI extArcTo(HDC, int, int, int, int, int, int, int, int);
extern BOOL WINAPI extLineTo(HDC, int, int);
extern int WINAPI extSetDIBitsToDevice(HDC, int, int, DWORD, DWORD, int, int, UINT, UINT, const VOID *, const BITMAPINFO *, UINT);
extern HBITMAP WINAPI extCreateCompatibleBitmap(HDC, int, int);
extern COLORREF WINAPI extSetPixel(HDC, int, int, COLORREF);
extern BOOL WINAPI extEllipse(HDC, int, int, int, int);
extern BOOL WINAPI extPolygon(HDC, const POINT *, int);
extern BOOL WINAPI extArc(HDC, int, int, int, int, int, int, int, int);
extern BOOL WINAPI extMaskBlt(HDC, int, int, int, int, HDC, int, int, HBITMAP, int, int, DWORD);
extern BOOL WINAPI extSetViewportOrgEx(HDC, int, int, LPPOINT);
extern BOOL WINAPI extSetViewportExtEx(HDC, int, int, LPSIZE);
extern BOOL WINAPI extGetViewportOrgEx(HDC, LPPOINT);
extern BOOL WINAPI extGetViewportExtEx(HDC, LPPOINT);
extern BOOL WINAPI extGetWindowOrgEx(HDC, LPPOINT);
extern BOOL WINAPI extSetWindowExtEx(HDC, int, int, LPPOINT);
extern BOOL WINAPI extSetWindowOrgEx(HDC, int, int, LPPOINT);
extern BOOL WINAPI extGetCurrentPositionEx(HDC, LPPOINT);
extern BOOL WINAPI extCreateScalableFontResourceA(DWORD, LPCTSTR, LPCTSTR, LPCTSTR);
extern int WINAPI extAddFontResourceA(LPCTSTR);
extern int WINAPI extAddFontResourceW(LPCWSTR);
extern int WINAPI extRemoveFontResourceA(LPCTSTR);
extern int WINAPI extRemoveFontResourceW(LPCWSTR);
extern BOOL WINAPI extCreateScalableFontResourceW(DWORD, LPCWSTR, LPCWSTR, LPCWSTR);
extern BOOL WINAPI extAnimatePalette(HPALETTE, UINT, UINT, const PALETTEENTRY *);
extern UINT WINAPI extSetSystemPaletteUse(HDC, UINT);
extern BOOL WINAPI extGDISetPixelFormat(HDC, int, const PIXELFORMATDESCRIPTOR *);
extern int WINAPI extGDIGetPixelFormat(HDC);
extern int WINAPI extChoosePixelFormat(HDC, const PIXELFORMATDESCRIPTOR *);
extern int WINAPI extDescribePixelFormat(HDC, int, UINT, LPPIXELFORMATDESCRIPTOR);
extern DWORD WINAPI extGetObjectType(HGDIOBJ);
extern int WINAPI extSetDIBits(HDC, HBITMAP, UINT, UINT, const VOID *, const BITMAPINFO *, UINT);
extern COLORREF WINAPI extGetPixel(HDC, int, int);
extern BOOL WINAPI extPlgBlt(HDC, const POINT *, HDC, int, int, int, int, HBITMAP, int, int);
extern BOOL WINAPI extSetPixelV(HDC, int, int, COLORREF);
extern BOOL WINAPI extChord(HDC, int, int, int, int, int, int, int, int);
extern BOOL WINAPI extPolyTextOutA(HDC, const POLYTEXTA *, int);
extern BOOL WINAPI extPolyTextOutW(HDC, const POLYTEXTW *, int);
extern int WINAPI extGetDIBits(HDC, HBITMAP, UINT, UINT, LPVOID, LPBITMAPINFO, UINT);
extern HBITMAP WINAPI extCreateDIBitmap(HDC, BITMAPINFOHEADER *, DWORD, const VOID *, const BITMAPINFO *, UINT);
extern HBITMAP WINAPI extCreateDIBSection(HDC, const BITMAPINFO *, UINT, VOID **, HANDLE, DWORD);
extern BOOL WINAPI extExtFloodFill(HDC, int, int, COLORREF, UINT);
extern HBITMAP WINAPI extCreateDiscardableBitmap(HDC, int, int);
extern BOOL WINAPI extGdiAlphaBlend(HDC, int, int, int, int, HDC, int, int, int, int, BLENDFUNCTION);
extern BOOL WINAPI extGdiGradientFill(HDC, PTRIVERTEX, ULONG, PVOID, ULONG, ULONG);
extern BOOL WINAPI extGdiTransparentBlt(HDC, int, int, int, int, HDC, int, int, int, int, UINT);
extern BOOL WINAPI extPie(HDC, int, int, int, int, int, int, int, int);
extern BOOL WINAPI extAngleArc(HDC, int, int, DWORD, FLOAT, FLOAT);
extern BOOL WINAPI extPolyPolyline(HDC, const POINT *, const DWORD *, DWORD);
extern BOOL WINAPI extFillRgn(HDC, HRGN, HBRUSH);
extern BOOL WINAPI extFrameRgn(HDC, HRGN, HBRUSH, int, int);
extern BOOL WINAPI extInvertRgn(HDC, HRGN);
extern BOOL WINAPI extPaintRgn(HDC, HRGN);
extern int WINAPI extSetMapMode(HDC, int);
extern BOOL WINAPI extRoundRect(HDC, int, int, int, int, int, int);
extern BOOL WINAPI extPolyPolygon(HDC, const POINT *, const INT *, int);
//extern BOOL WINAPI extDPtoLP(HDC, LPPOINT, int);
extern BOOL WINAPI extPlayEnhMetaFile(HDC, HENHMETAFILE, const RECT *);
extern UINT WINAPI extSetPaletteEntries(HPALETTE, UINT, UINT, const PALETTEENTRY *);
extern int WINAPI extSetROP2(HDC, int);
extern BOOL WINAPI extGetTextExtentPointA(HDC, LPCTSTR, int, LPSIZE);
extern BOOL WINAPI extGetTextExtentPoint32A(HDC, LPCTSTR, int, LPSIZE);
extern HGDIOBJ WINAPI extSelectObject(HDC, HGDIOBJ);
extern BOOL WINAPI extDeleteObject(HGDIOBJ);
extern int WINAPI extSelectClipRgn(HDC, HRGN);
extern int WINAPI extExtSelectClipRgn(HDC, HRGN, int);
extern int WINAPI extGetClipRgn(HDC, HRGN);
extern int WINAPI extOffsetClipRgn(HDC, int, int);
extern int WINAPI extIntersectClipRect(HDC, int, int, int, int);
extern int WINAPI extExcludeClipRect(HDC, int, int, int, int);


